### ISSUE TITLE
Switch to JS

### ISSUE THREAD

**Issue by ghost** [calebwin/digital-tower-defense-simulator#1]
Not really an issue but since you don't have a feature request page it is an issue. 

Instead of using P5.js kindly use the canvas element for drawing purposes. 

The reason being that P5.js is an obsolete library which imo serves no purpose among multiple reasons. 

# Note : 
This is just my opinion and you can disagree with it.

**Comment by calebwin** [comment]
Thanks. Personally, I love p5.js; it's my favorite non-webgl 2d JS graphics library. But I do agree that using the canvas element is probably better than using p5.js. I will try to migrate as soon as I can.

**Comment by ghost** [comment]
@calebwin 

If you like P5.js then you could (that is if you want) have two versions of it. One in P5.js and other using `canvas` element for drawing.

---

Closed since this is not an issue.
